### ISSUE TITLE
Setting to change size of icons

### ISSUE THREAD

**Issue by HHest** [peterfajdiga/FastDraw#12]
Just discovered FastDraw. Thanks for å great app. 

Would be nice to have a way to change the size of the icons. I feel they are a little large at the moment, and because I am using a fairly large widget, I wish I could see more apps at one time, without having to scroll. Thank you.

**Comment by peterfajdiga** [comment]
Hi, are the icons too large on a phone or on a tablet?

**Comment by HHest** [comment]
Too large on my phone. I would like to squeeze in more icons. Thanks.

**Comment by peterfajdiga** [comment]
Sorry for the delay. It's a good suggestion, but it's not something I'd like to implement and maintain. I'd prefer this app to have sane icon sizes without needing configuration. If you think I should change the icon size for a particular screen size/density, please let me know.
