### ISSUE TITLE
Custom position of apps in custom category.

### ISSUE THREAD

**Issue by sandoxy** [peterfajdiga/FastDraw#14]
Hi,

it would be great, if I one could change the position of the apps in a custom category manually. For example, I would like to have my dialer at the bottom in the left corner and not changing place, after adding new apps to the category. Maybe an optional deactivating of alphabetical sorting and then adding apps to free space could help doing it.

Thanks

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion! I agree it would be nice to have this option, but it would be too much work to implement for something I wouldn't use. Sorry. I am planning to add an option to sort items by most frequently used, though, if that would help.

**Comment by sandoxy** [comment]
Thank you for your answer. I can understand your argument.
