### ISSUE TITLE
[FEATURE REQUEST] Make category tabs hideable

### ISSUE THREAD

**Issue by HarriBuh** [peterfajdiga/FastDraw#23]
Right now all categories will always be expanded when switching.
This is kind of annoying when you have a widget (f.e. of your calendar app) at the to of your screen, effectively halving it.

Check this screenshot for reference:
![Screenshot_20240206-163928.png](https://github.com/peterfajdiga/FastDraw/assets/123186113/1466b781-f4f2-4671-8c98-243220566c1b)

There already is an experimental feature that enables scrolling down if there were to many shortcuts present- maybe you can use this to enable moving up and down the whole category  tabs, too?
Like press and hold your finger on the tab bar to move it either up or down..

EDIT:
I just figured out how to expand the widget size, which goes even further in the right direction:

![obscura1707234884682.jpg](https://github.com/peterfajdiga/FastDraw/assets/123186113/e2c989b2-9d59-47ad-a809-81977b36bd5f)

Now the only thing left to do would be to completely hide the shortcuts while keeping the tab bar visible- just like the regular dock (bar) on Android's vanilla launcher. Is this possible?

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion. The problem is that widgets hijack vertical scrolling. A widget large enough to completely hide the app items would make it impossible to scroll down to the app items.
