### ISSUE TITLE
[Request] List view

### ISSUE THREAD

**Issue by teemue** [peterfajdiga/FastDraw#27]
An option to show icons as a list instead of a grid. And option to choose the icon size.

**Comment by peterfajdiga** [comment]
I've actually experimented with a list view, but it didn't look that nice. I think grid view fits the layout of this launcher much better.

Icon size setting has been suggested before (#12), but I prefer to make icon size adapt to the screen size automatically. If you think I should change the icon size for a particular screen size/density, please let me know.

You can also try changing the global DPI setting.
