### ISSUE TITLE
Icon pack support 

### ISSUE THREAD

**Issue by Donnnno** [peterfajdiga/FastDraw#28]
It would be great if FastDraw supported icon packs, like most launchers do. It gives the users more freedom to customize their homescreen :)

**Comment by peterfajdiga** [comment]
Duplicate of #13.

I agree it would be great, but I don't have the time to implement and maintain most of the other launcher's features. :(

Seeing that this is a popular request, I'll leave the issue open.

**Comment by peterfajdiga** [comment]
Duplicate of #13.

I agree it would be great, but I don't have the time to implement and maintain most of the other launcher's features. :(

Seeing that this is a popular request, I'll re-open the original issue.

**Comment by Donnnno** [comment]
Totally understandable, I understand the struggle of not having enough time to maintain a project.
