### ISSUE TITLE
Change request: Align app icons to bottom when tabs aligned at bottom

### ISSUE THREAD

**Issue by MortenJuhl-Johansen** [peterfajdiga/FastDraw#36]
Aligning the tabs at the bottom is a great feature, because the thumb is closer to the bottom when using just one hand.
But if only a few icons are in that tab, they appear at the top! 
So my suggestion is, maybe it makes more sense to align them towards the bottom closer to the tabs?
![Screenshot_2024-07-08-22-11-47-35_4a5233be5554eaec39e05b9767dead00](https://github.com/peterfajdiga/FastDraw/assets/155162133/9442d5e1-868b-4f18-8b7a-727c59959078)

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion! I agree this would be nice, but unfortunately it's not doable[^1] because of nested scrolling. The bottom icons would be placed below the screen and wouldn't be visible.

[^1]: Maybe with some hacks, but it wouldn't be nice.
