### ISSUE TITLE
Support for Backup and Restore

### ISSUE THREAD

**Issue by subaru22b** [peterfajdiga/FastDraw#41]
I would like to request the addition of a backup and restore feature. This functionality would allow users to easily save their apps categorization, and restore them when needed, providing a seamless experience during device upgrades, resets, or launcher reinstallation. This option would help users stick and commit their time with the app, as they would be able to back up and restore their categorization, ensuring a more personalized and efficient experience.

Thank you!

**Comment by peterfajdiga** [comment]
Hi, this is something I haven't tested yet. I thought it should work out of
the box. Which app data backup app/service did you use (like Titanium
Backup or Google One)?

**Comment by subaru22b** [comment]
I actually don't use those apps like Titanium Backup or Google One. I'm looking for an option to export the settings instead. I found apps like LawnchairLauncher that can create backups and restore them.

**Comment by peterfajdiga** [comment]
Aha, got it, thanks. This is out of scope for this app, sorry.
