### ISSUE TITLE
Setting to change the size of thé grid

### ISSUE THREAD

**Issue by acress1** [peterfajdiga/FastDraw#5]
Right now the size of the app grid is fixed to 4 colums, could be cool to be able to chose :)

**Comment by peterfajdiga** [comment]
The number of columns is actually not fixed, but depends on the width of the screen and DPI density. Try changing the DPI density (aka Display size) in the system settings and Fast Draw should adapt accordingly.

**Comment by lianergoist** [comment]
> The number of columns is actually not fixed, but depends on the width of the screen and DPI density. Try changing the DPI density (aka Display size) in the system settings and Fast Draw should adapt accordingly.

I can't find where I can change DPI density. But anyway, wouldn't that change it for all apps?

I used to use Discrete Launcher (not maintained anymore) and the developer added an option to change the size of the icons on my suggestion. I actually came here to suggest you to do the same.

**Comment by peterfajdiga** [comment]
Thanks for the suggestion, but this is not a setting I want to implement and maintain. The goal of Fast Draw is to have a sensible icon size without having to configure it, but I admit the app is not optimized for or even tested on tablets. Do the icons appear too small there?

**Comment by lianergoist** [comment]
> Do the icons appear too small there?

In my opinion, yes. First image is Fast Draw, next is Lenovo launcher, third is Discreet Launcher where I have changed icon size.

![Screenshot_20231115-085937](https://github.com/peterfajdiga/FastDraw/assets/6023573/8437a7e6-6221-4ab9-92fe-1a7f1972eda5)

![Screenshot_20231115-085534](https://github.com/peterfajdiga/FastDraw/assets/6023573/9d3440f6-ffaf-44ff-b741-3e7e0a970f37)

![Screenshot_20231115-090147](https://github.com/peterfajdiga/FastDraw/assets/6023573/397441ef-788b-4e45-9b53-8956ef371927)

**Comment by peterfajdiga** [comment]
Thanks for the screenshots. I agree, it looks too dense on a tablet. I've made the icons slightly bigger and increased the spacing between them on tablets. This change is included in version 2.0.

**Comment by peterfajdiga** [comment]
I'm closing the original issue as not planned because I don't want to introduce too many options. In my humble opinion the global DPI setting should be used to achieve a denser or sparser display.
