### ISSUE TITLE
Multiple Rows For Categories

### ISSUE THREAD

**Issue by mtekman** [peterfajdiga/FastDraw#7]
Currently "categories" take up a single row which is full of many narrow icons under the default mode, or a scrollable list in the experimental mode.

Could we specify how many rows we want our categories spread over?

**Comment by peterfajdiga** [comment]
Hi, thanks for the suggestion. Fast Draw uses TabLayout for the category tabs and unfortunately TabLayout doesn't support multiple rows of tabs.

**Comment by mtekman** [comment]
Oh I see, thanks for telling me about the internals I had no idea about the implementation.

I looked just now for any custom workarounds that could wrap the TabLayout, but I didn't find anything. Your scrollable fix is a pretty good one then in this regard.

If this is a WONTFIX, feel free to close this PR

**Comment by peterfajdiga** [comment]
I'm closing this issue, thanks again for the report!
